language: ruby
rvm:
- 2.6.3
install:
- bundle install
script: bundle exec rake site:deploy --quiet
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - secure: jlS+XJPNPBiaRQH5/w5wX9TUybPTFw++DILTZd5DXR88QxknN/+/PIjYYpHliZat1az2lqIM/87kLQNAXXqei79n1KD5KfNImDBKI7TUbP9799Wv/a1ypq9/Uiip3GSVamH/mXRqRdORClWcpEwTIUNpWNiPxzYqaIDp75PFJ34pSYzCKnFk32p0IiuC/PTp4DuXc1QjN5OkJWflQ9NT5hZjAJQibCGKaMF2zE8aIYJm7TZbqrMqHlBF4i9FkaOkYADW/0UeB70Xv2dtMmxedMX2g0U/351q3/UrurX76zG+W7EclDKwKWneOnbJRcgZaTHx73BwCO6TJh3K38jLuwTA4wPxzItKv7CiDeD5yLbNBYw755TtBiQzQXdba7kX9cNNGCPqWwBcDql6r7kFMJq8OkVwLkN54TirEIyHnCBoxRaawsE5FnmkDRDB1PipIkaPyMouL6a66KAM0KR7gjqkSSq7cO7Rj6SjaZyL6d0cVryI30hW3Z0hE3ilfO7thE6CPXSolkjYHDlliteYTeOQcVSh2H6WR8af2Cm1qUYP2OjTMreILjgD0/DFXezF84A1skA4YGB22H6J63l9F7L2339XVBYVaEcILd4fLQXqy3zDj5SsuHPyBU/LzdubnupNIop6A1l0WfYGT7RrXc1/jSEvYbef34yVpSl4n3I=
exclude:
- vendor
branches:
  only:
  - master
