language: ruby
rvm:
- 2.6.3
install:
- bundle install
script: bundle exec rake site:deploy --quiet
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - secure: GFSmThn6RxId666K9W7M6DTMY5etCrVMPLjUzuvHME1KNKVdqTx8Ka3XHvB6uIJHn5a+SJAgYdmysA06LQ0xnIEm/L+qR2+yDtGa8xg8nqebeKSoGNi0QKf3OqbCRb6QxikTHqiiQmurKPAMI3XzcRYwcWEvJbMtaPsOT4DmgxPtnvxVEK4w7wW/LS1XhEUrVeyJ7LJShyStxH+YZ06Xi7sz3KFSMAJ6ASc6ASh/vZ9Z7RPP2w5mv3IKnw2lFWsjFnZR+tfxgAO2MP1HdC7NDnxAScsKqOgpg59VVrNpVRtBPEWQ+LaMNm1GHTxw+xrBNvuKnYrnjCOMEphfPNtV4sWyn5iFcxJ45x0lMdym/IaZWk4gw7bDN7n+8YGQHQkrmTDBuCYLuBY4RpGBeLGiWQU9LDeGLB9JFG4zx7wYa6Daqa7LXcmjTgkL1MTwvFxBc5lqL5LsOO5rJVd+O6m0O5IEbM5LfvduPQjK/DLnTvC30fxjpxDwwukaFPL+9Xgu2pDjr4ktCLKD4CxOULimEjOM6a0GS4zSmA1oqZm2xXHT8eLR7a1WpHFMU2DKQLmZ6Xu8yeM0wGkXrtbxjVH0wEYrFpwTXeCneDGSoaGCVSsaRJIyXf8semXdNOzaYYCuK+49qTBQkd1Bzf7XMw8It4TocO0Q+e0Unrrw68p5nfM=
exclude:
- vendor
branches:
  only:
  - master
